"""ubicaciones de sucursales

Revision ID: 0e922de1ab5a
Revises: 3188edce6362
Create Date: 2026-09-01 20:00:02.472549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e922de1ab5a'
down_revision: Union[str, Sequence[str], None] = '3188edce6362'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geocode_cache',
    sa.Column('query', sa.String(length=300), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('display_name', sa.String(length=500), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('query')
    )
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('province', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('location_postal_code', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('location_source', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('located_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_stores_location_postal_code'), ['location_postal_code'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stores_location_postal_code'))
        batch_op.drop_column('located_at')
        batch_op.drop_column('location_source')
        batch_op.drop_column('location_postal_code')
        batch_op.drop_column('province')
        batch_op.drop_column('city')
        batch_op.drop_column('address')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    op.drop_table('geocode_cache')
    # ### end Alembic commands ###
