"""perfil, domicilios y listas de compras

Revision ID: 3188edce6362
Revises: 8d850122bcb6
Create Date: 2026-09-01 19:04:39.601869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3188edce6362'
down_revision: Union[str, Sequence[str], None] = '8d850122bcb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('street', sa.String(length=200), nullable=True),
    sa.Column('number', sa.String(length=20), nullable=True),
    sa.Column('floor', sa.String(length=20), nullable=True),
    sa.Column('apartment', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('province', sa.String(length=120), nullable=True),
    sa.Column('postal_code', sa.String(length=16), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'label', name='uq_address_user_label')
    )
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_addresses_user_id'), ['user_id'], unique=False)

    op.create_table('shopping_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_list_user_name')
    )
    with op.batch_alter_table('shopping_lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shopping_lists_user_id'), ['user_id'], unique=False)

    op.create_table('user_profile',
    sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('postal_code', sa.String(length=16), nullable=True),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('sales_channel', sa.Integer(), nullable=True),
    sa.Column('theme', sa.String(length=16), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('dni', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('shopping_list_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=120), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('ean', sa.String(length=14), nullable=True),
    sa.Column('pinned_label', sa.String(length=400), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['shopping_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shopping_list_lines', schema=None) as batch_op:
        batch_op.create_index('ix_line_list_position', ['list_id', 'position'], unique=False)
        batch_op.create_index(batch_op.f('ix_shopping_list_lines_list_id'), ['list_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_list_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shopping_list_lines_list_id'))
        batch_op.drop_index('ix_line_list_position')

    op.drop_table('shopping_list_lines')
    op.drop_table('user_profile')
    with op.batch_alter_table('shopping_lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shopping_lists_user_id'))

    op.drop_table('shopping_lists')
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_addresses_user_id'))

    op.drop_table('addresses')
    # ### end Alembic commands ###
