"""esquema inicial

Revision ID: 8d850122bcb6
Revises: 
Create Date: 2026-09-01 19:04:06.518664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d850122bcb6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('supports_store_prices', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chains', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chains_slug'), ['slug'], unique=True)

    op.create_table('payment_instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('issuer_slug', sa.String(length=64), nullable=False),
    sa.Column('brand', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('rails', sa.JSON(), nullable=False),
    sa.Column('bins', sa.JSON(), nullable=False),
    sa.Column('bin_source', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_promotions', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'label', name='uq_instrument_user_label')
    )
    with op.batch_alter_table('payment_instruments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_instruments_issuer_slug'), ['issuer_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_instruments_user_id'), ['user_id'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ean', sa.String(length=14), nullable=True),
    sa.Column('name', sa.String(length=400), nullable=False),
    sa.Column('brand', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_ean'), ['ean'], unique=True)

    op.create_table('promo_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('used_cents', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'rule_id', 'period_start', name='uq_usage_user_rule_period')
    )
    with op.batch_alter_table('promo_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_promo_usage_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_promo_usage_user_id'), ['user_id'], unique=False)

    op.create_table('chain_skus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('external_product_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=400), nullable=False),
    sa.Column('brand', sa.String(length=200), nullable=True),
    sa.Column('ean', sa.String(length=14), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('link', sa.String(length=1000), nullable=True),
    sa.Column('measurement_unit', sa.String(length=16), nullable=True),
    sa.Column('unit_multiplier', sa.Float(), nullable=False),
    sa.Column('category_path', sa.JSON(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chain_id'], ['chains.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chain_id', 'sku_id', name='uq_sku_chain_sku')
    )
    with op.batch_alter_table('chain_skus', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chain_skus_chain_id'), ['chain_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chain_skus_ean'), ['ean'], unique=False)
        batch_op.create_index(batch_op.f('ix_chain_skus_product_id'), ['product_id'], unique=False)

    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sales_channel', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.String(length=512), nullable=True),
    sa.Column('postal_code', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['chain_id'], ['chains.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chain_id', 'external_id', name='uq_store_chain_external')
    )
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stores_chain_id'), ['chain_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stores_postal_code'), ['postal_code'], unique=False)

    op.create_table('price_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chain_sku_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.String(length=64), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('reference_price_cents', sa.Integer(), nullable=True),
    sa.Column('price_per_unit_cents', sa.Integer(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('available_quantity', sa.Integer(), nullable=False),
    sa.Column('price_scope', sa.String(length=16), nullable=False),
    sa.Column('promotions', sa.JSON(), nullable=True),
    sa.Column('promo_digest', sa.String(length=64), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chain_sku_id'], ['chain_skus.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_snapshots_chain_sku_id'), ['chain_sku_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_snapshots_store_id'), ['store_id'], unique=False)
        batch_op.create_index('ix_snapshot_lookup', ['chain_sku_id', 'store_id', 'observed_at'], unique=False)
        batch_op.create_index('ix_snapshot_observed', ['observed_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_snapshot_observed')
        batch_op.drop_index('ix_snapshot_lookup')
        batch_op.drop_index(batch_op.f('ix_price_snapshots_store_id'))
        batch_op.drop_index(batch_op.f('ix_price_snapshots_chain_sku_id'))

    op.drop_table('price_snapshots')
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stores_postal_code'))
        batch_op.drop_index(batch_op.f('ix_stores_chain_id'))

    op.drop_table('stores')
    with op.batch_alter_table('chain_skus', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chain_skus_product_id'))
        batch_op.drop_index(batch_op.f('ix_chain_skus_ean'))
        batch_op.drop_index(batch_op.f('ix_chain_skus_chain_id'))

    op.drop_table('chain_skus')
    with op.batch_alter_table('promo_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promo_usage_user_id'))
        batch_op.drop_index(batch_op.f('ix_promo_usage_rule_id'))

    op.drop_table('promo_usage')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_ean'))

    op.drop_table('products')
    with op.batch_alter_table('payment_instruments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_instruments_user_id'))
        batch_op.drop_index(batch_op.f('ix_payment_instruments_issuer_slug'))

    op.drop_table('payment_instruments')
    with op.batch_alter_table('chains', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chains_slug'))

    op.drop_table('chains')
    # ### end Alembic commands ###
