"""domicilios ubicados y sucursales manuales

Revision ID: f670931b07ad
Revises: 0e922de1ab5a
Create Date: 2026-09-01 21:59:03.417448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f670931b07ad'
down_revision: Union[str, Sequence[str], None] = '0e922de1ab5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('province', sa.String(length=120), nullable=True),
    sa.Column('postal_code', sa.String(length=16), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('geo_source', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chain_id'], ['chains.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'chain_id', 'name', name='uq_custom_store_name')
    )
    with op.batch_alter_table('custom_stores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custom_stores_chain_id'), ['chain_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom_stores_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('geo_source', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('geo_label', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_column('geo_label')
        batch_op.drop_column('geo_source')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    with op.batch_alter_table('custom_stores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custom_stores_user_id'))
        batch_op.drop_index(batch_op.f('ix_custom_stores_chain_id'))

    op.drop_table('custom_stores')
    # ### end Alembic commands ###
